### ISSUE TITLE
What are some of the differences between this and Litestream?

### ISSUE THREAD

**Issue by NatElkins** [lichuang/replited#2]
Is it just that this project is written in Rust, or is there something beyond that?

Interesting project, keep up the good work!

**Comment by lichuang** [comment]
For now, replited has just started, the initial ideas were inspired by litestream, such as how to use sqlite wal to achieve incremental replication of sqlite data, and now the biggest difference with litestream is that because of the use of [opendal](https://github.com/apache/opendal), so it will be easier to support the other kind storage backends, litestream only supports s3/sftp/gcs/local fs.
